/*
-- Query: SELECT * FROM book_store.book
LIMIT 0, 1000

-- Date: 2021-06-25 21:20
*/
INSERT INTO `book` (`id`,`title`,`publishing_year`,`PUBLISHER_id`,`description`,`image`) VALUES (1,'Alisa u zemlji cuda',1865,2,'Glavna junakinja u ovoj knjizi je devojčica Alisa,koja odlazi u nestvarnu Zemlju Čuda, koja postoji samo u njenim snovima. U Zemlji Čuda ona se susreće i druži sa mnogo neobičnih životinja i likova, te stvarima i predmetima koje su bili živi, a sa kojima doživljava razne zgode i nezgode...','alisa2');
INSERT INTO `book` (`id`,`title`,`publishing_year`,`PUBLISHER_id`,`description`,`image`) VALUES (2,'Hamlet',1570,3,'Danski kralj iznenada umire. Njegov brat Klaudije nasljeđuje prijestolje i ženi se njegovom udovicom. Duh kralja se prikazuje kraljevom sinu Hamletu i kazuje mu da ga je Klaudije ubio da bi dobio prijestolje i ženu. Da bi lakše dokazao stričevu krivnju Hamlet odluči glumiti luđaka...','hamlet');
INSERT INTO `book` (`id`,`title`,`publishing_year`,`PUBLISHER_id`,`description`,`image`) VALUES (3,'Orlovi rano lete',1959,4,'U ovom romanu se govori o grupi dječaka.Vođa dječaka je bio Jovanče a osim njega tu su bili Lazar Mačak, Stric, Đoko Potrk, Nikolca prikolca i djevojčica Lunja.Oni pomažu partizanima i otkrivaju im tajnu pećinu. Oni učestvuju u obrani svog sela zajedno sa borcima i postaju partizanski kuriri...','orlovi1');
INSERT INTO `book` (`id`,`title`,`publishing_year`,`PUBLISHER_id`,`description`,`image`) VALUES (4,'Ana Karenjina',1983,1,'Ana Karenjina, pre svega, govori o dve parelene ljubavne priče: strasne, nesrećne i  destruktivne ljubavi između Ane Karenjine i grofa Vronskog i stabilne ljubavi između Ljevina i Kiti. Takođe, obrađuje ne samo brak i porodicu već i ekonomske i društvene odnose u tadašnjoj Rusiji...','ana2');
INSERT INTO `book` (`id`,`title`,`publishing_year`,`PUBLISHER_id`,`description`,`image`) VALUES (5,'Koreni',1954,4,'Radnja romana je smeštena na kraj 19. veka u izmišljeno selo Prerovo u vreme političkih promena i građanskih previranja i prati živote Aćima Katića, uglednog čoveka starog kova i radikalnih uverenja, i njegovih sinova Vukašina i Đorđa...','koreni');
INSERT INTO `book` (`id`,`title`,`publishing_year`,`PUBLISHER_id`,`description`,`image`) VALUES (6,'Zlocin i kazna',1848,2,'Glavni je junak romana siromašan student prava Rodion Raskoljnjikov. Raskoljnjikova progoni ideja o izvršenju “više pravde” koju će ostvariti ubojstvom Aljone Ivanove...','zlocin1');
INSERT INTO `book` (`id`,`title`,`publishing_year`,`PUBLISHER_id`,`description`,`image`) VALUES (7,'Dervis i smrt',1966,3,'Derviš i smrt po vrsti je psihološki i filozofski roman, pun introspekcija glavnog lika, kojima on traži smisao života. Roman se sastoji od šesnaest poglavlja, a podijeljen je na dva dijela..','dervis1');
INSERT INTO `book` (`id`,`title`,`publishing_year`,`PUBLISHER_id`,`description`,`image`) VALUES (8,'Na Drini cuprija',1945,2,'Roman Na Drini ćuprija je najpoznatije delo našeg nobelovca Ive Andrića. U romanu se radnja odigrava oko mosta na Drini u Višegradu. Na početku romana Andrić objašnjava kako su se ljudi snalazili dok mosta nije bilo, izgradnja most i kasnije životne priče ljudi koji su živeli oko njega. Most je u romanu simbol čvrste građevine koja je večno prisutna, dok su ljudski životi prolazni..','drina1');
INSERT INTO `book` (`id`,`title`,`publishing_year`,`PUBLISHER_id`,`description`,`image`) VALUES (9,'Starac i more',1949,3,'Starac Santijago bio je siromašni ribar koji je sam ribario u malom čamcu u Golfskoj struji, već osamdeset i četiri dana. Prvih četrdeset dana društvo mu je pravio dečak Manolino, ali su nakon toga dečakovi roditelji rekli da starca prati zla sreća, pa se dečak morao prebaciti na drugi ribarski brod...','starac1');
INSERT INTO `book` (`id`,`title`,`publishing_year`,`PUBLISHER_id`,`description`,`image`) VALUES (10,'Necista krv',1910,4,'Jedan mlad zivot je unisten. I pre pocetka Sofka je dozivela kraj. Dozivela je tezak slom i vise se nije oporavila, niti se trudila da joj bude bolje. Predala se, izgubila svu svoju lepotu, izgubila svetlo na kraju tunela. Nemilosrdno je unistena kao zena, kao majka, kao individua. Zaista tragicna sudbina!','krv');
INSERT INTO `book` (`id`,`title`,`publishing_year`,`PUBLISHER_id`,`description`,`image`) VALUES (11,'Stranac',1942,1,'U romanu je pripovjedač ujedno lik Mersault. Roman je pisan u prvom licu, no događaji se iznose iznimno objektivno i precizno (a lik govori o sebi kao da govori o nekome drugom i ne trudi se osmisliti svoj život u okviru nekog zadanog sustava vrijednosti jer njegov je život posve iskren, stoga mu ne traži opravdanje)..','stranac1');
INSERT INTO `book` (`id`,`title`,`publishing_year`,`PUBLISHER_id`,`description`,`image`) VALUES (12,'Oblak',1948,1,'Pesma govori o oblaku koji se nadvio nad gradom. Oblak je bio prekrasan, ali nitko od ljudi iz grada nije ni primetio njegovu lepotu, jer su bili zauzeti „zemnim“ stvarima, ljudima očito previše važnim da bi ih na trenutak zapostavili zbog jednog (običnog) oblaka. Iako je oblak „krvario lepotu“, to nije bilo dovoljno da ga se primeti. Na kraju se uzdigao visoko na nebo, toliko da ga je vetar s vremenom raznio...','oblak');
INSERT INTO `book` (`id`,`title`,`publishing_year`,`PUBLISHER_id`,`description`,`image`) VALUES (13,'Plava grobnica',1917,4,'Govori o srpskim vojnicima koje su nakon smrti bacali u Jonsko more, pored ostrva Krfa, tako stvorivši masovnu grobnicu u morskim dubinama, koju su činila tela od skoro 5 000 vojnika. Ta grobnica opevana je kao večno počivalište hrabrih...','grobnica');
INSERT INTO `book` (`id`,`title`,`publishing_year`,`PUBLISHER_id`,`description`,`image`) VALUES (35,'crv mali',1212,2,'','noimage');
INSERT INTO `book` (`id`,`title`,`publishing_year`,`PUBLISHER_id`,`description`,`image`) VALUES (37,'bfd',1231,3,'','noimage');
