-- MySQL Script generated by MySQL Workbench
-- Fri Jun 25 21:28:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema book_store
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `book_store` ;

-- -----------------------------------------------------
-- Schema book_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `book_store` DEFAULT CHARACTER SET utf8 ;
USE `book_store` ;

-- -----------------------------------------------------
-- Table `book_store`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store`.`author` ;

CREATE TABLE IF NOT EXISTS `book_store`.`author` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `birth_place` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `book_store`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store`.`book` ;

CREATE TABLE IF NOT EXISTS `book_store`.`book` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `publishing_year` INT(11) NOT NULL,
  `PUBLISHER_id` INT(11) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `image` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_BOOK_PUBLISHER1_idx` (`PUBLISHER_id` ASC) VISIBLE,
  CONSTRAINT `fk_BOOK_PUBLISHER1`
    FOREIGN KEY (`PUBLISHER_id`)
    REFERENCES `book_store`.`publisher` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `book_store`.`book_has_author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store`.`book_has_author` ;

CREATE TABLE IF NOT EXISTS `book_store`.`book_has_author` (
  `BOOK_id` INT(11) NOT NULL,
  `AUTHOR_id` INT(11) NOT NULL,
  PRIMARY KEY (`BOOK_id`, `AUTHOR_id`),
  INDEX `fk_BOOK_has_AUTHOR_AUTHOR1_idx` (`AUTHOR_id` ASC) VISIBLE,
  INDEX `fk_BOOK_has_AUTHOR_BOOK_idx` (`BOOK_id` ASC) VISIBLE,
  CONSTRAINT `fk_BOOK_has_AUTHOR_AUTHOR1`
    FOREIGN KEY (`AUTHOR_id`)
    REFERENCES `book_store`.`author` (`id`),
  CONSTRAINT `fk_BOOK_has_AUTHOR_BOOK`
    FOREIGN KEY (`BOOK_id`)
    REFERENCES `book_store`.`book` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `book_store`.`book_store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store`.`book_store` ;

CREATE TABLE IF NOT EXISTS `book_store`.`book_store` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `work_time` VARCHAR(45) NULL DEFAULT NULL,
  `opening_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `book_store`.`book_store_has_book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store`.`book_store_has_book` ;

CREATE TABLE IF NOT EXISTS `book_store`.`book_store_has_book` (
  `BOOK_STORE_id` INT(11) NOT NULL,
  `BOOK_id` INT(11) NOT NULL,
  `quantity` INT(11) NOT NULL DEFAULT '0',
  `price` VARCHAR(5) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`BOOK_STORE_id`, `BOOK_id`),
  INDEX `fk_BOOK_STORE_has_BOOK_BOOK1_idx` (`BOOK_id` ASC) VISIBLE,
  INDEX `fk_BOOK_STORE_has_BOOK_BOOK_STORE1_idx` (`BOOK_STORE_id` ASC) VISIBLE,
  CONSTRAINT `fk_BOOK_STORE_has_BOOK_BOOK1`
    FOREIGN KEY (`BOOK_id`)
    REFERENCES `book_store`.`book` (`id`),
  CONSTRAINT `fk_BOOK_STORE_has_BOOK_BOOK_STORE1`
    FOREIGN KEY (`BOOK_STORE_id`)
    REFERENCES `book_store`.`book_store` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `book_store`.`book_store_has_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store`.`book_store_has_user` ;

CREATE TABLE IF NOT EXISTS `book_store`.`book_store_has_user` (
  `BOOK_STORE_id` INT(11) NOT NULL,
  `USER_id` INT(11) NOT NULL,
  PRIMARY KEY (`BOOK_STORE_id`, `USER_id`),
  INDEX `fk_BOOK_STORE_has_USER_USER1_idx` (`USER_id` ASC) VISIBLE,
  INDEX `fk_BOOK_STORE_has_USER_BOOK_STORE1_idx` (`BOOK_STORE_id` ASC) VISIBLE,
  CONSTRAINT `fk_BOOK_STORE_has_USER_BOOK_STORE1`
    FOREIGN KEY (`BOOK_STORE_id`)
    REFERENCES `book_store`.`book_store` (`id`),
  CONSTRAINT `fk_BOOK_STORE_has_USER_USER1`
    FOREIGN KEY (`USER_id`)
    REFERENCES `book_store`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `book_store`.`publisher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store`.`publisher` ;

CREATE TABLE IF NOT EXISTS `book_store`.`publisher` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(150) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `phone_number` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `book_store`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store`.`role` ;

CREATE TABLE IF NOT EXISTS `book_store`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `book_store`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_store`.`user` ;

CREATE TABLE IF NOT EXISTS `book_store`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `ROLE_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_USER_ROLE1_idx` (`ROLE_id` ASC) VISIBLE,
  CONSTRAINT `fk_USER_ROLE1`
    FOREIGN KEY (`ROLE_id`)
    REFERENCES `book_store`.`role` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
